# Dependencies
markdown:	    kramdown
highlighter:	pygments

# Permalinks
permalink:	    :title

# Setup
title:		    Mads's Blog
tagline:	    'blog'
description:	'My personal blog.'
baseurl:        "/blog"
url:            http://buchi.dk/
commentsystem:	google
disqus:		    example

author:
  name:		'Mads Buch'
  url:		https://plus.google.com/+MadsBuch

paginate:	5

# Custom vars
icon:		assets/images/icon.png
cover:		assets/images/cover.jpg

    
copyright:
  author:	Mads Buch
  url:		http://buchi.dk
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
