# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: "Joachim Harris"
description: >
   Technical articles

email: joachimharris@gmail.com

#blog logo
logo: "/assets/images/logo.png"

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Joachim Harris'
author: 'Joachim Harris'
author_image: "/assets/images/author.jpg"

paginate:	5

# Permalinks
permalink:	  :title/

# Dependencies
markdown:	    kramdown
highlighter:  rouge

url: "http://joachimharris.com" # the base hostname & protocol for your site
baseurl: "/blog"

###### SOCIAL

#used to display twitter cards
twitter_handle: '@joachimharris'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# Open Graph
fb_app_id: 1727612590830968

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/joachimharris
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/joachimharris
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
