# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: "Emil Illum Vandekerckhove"
description: >
   Technical articles

email: emil.vdk@gmail.com

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Emil Illum Vandekerckhove'
author: 'Emil Illum Vandekerckhove'
author_image: "/assets/images/author.jpg"

paginate:	5

# Permalinks
permalink:	  :title/

# Dependencies
markdown:	    kramdown
highlighter:  rouge

url: "http://emilillum.com" # the base hostname & protocol for your site
baseurl: "/techblog"

###### SOCIAL

#used to display twitter cards
twitter_handle: '@emilillum'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# Open Graph
fb_app_id: 1727612590830968

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/emilillum
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/emilillum.vandekerckhove
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/emilillum
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://plus.google.com/u/0/105915808449723228492
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
